### ISSUE TITLE
Failure building kata-containers on s390x

### ISSUE THREAD

**Issue by etrunko** [kata-containers/kata-containers#1204]
I am working on provinding kata-containers 2.0 package for Fedora, build fails only on s390x.

https://koji.fedoraproject.org/koji/taskinfo?taskID=57653053

```
   Compiling scan_fmt v0.2.5
   Compiling cgroups v0.1.1-alpha.0 (https://github.com/kata-containers/cgroups-rs?branch=stable-0.1.1#8717524f)
error[E0425]: cannot find value `CGROUP2_SUPER_MAGIC` in module `statfs`
   --> /builddir/build/BUILD/kata-containers-2.0.0/src/agent/vendor/cgroups/src/hierarchies.rs:230:51
    |
230 |     fs_stat.unwrap().filesystem_type() == statfs::CGROUP2_SUPER_MAGIC
    |                                                   ^^^^^^^^^^^^^^^^^^^ not found in `statfs`
    |
help: consider importing this constant
    |
11  | use libc::CGROUP2_SUPER_MAGIC;
    |
error: aborting due to previous error
For more information about this error, try `rustc --explain E0425`.
error: could not compile `cgroups`
```

**Comment by etrunko** [comment]
Complete build.log
[build.log](https://github.com/kata-containers/kata-containers/files/5712033/build.log)

**Comment by fidencio** [comment]
@Jakob-Naucke, have you faced this issue before? If so, how did you work this around?

**Comment by Jakob-Naucke** [comment]
Hi @fidencio @etrunko yes.
The root cause of this particular problem seems to be in [rust-lang/libc](https://github.com/rust-lang/libc), which kata-containers depends on through [kata-containers/cgroups-rs](https://github.com/kata-containers/cgroups-rs) and [nix-rust/nix](https://github.com/nix-rust/nix). The issue is that filesystem types are `uint` on s390x-linux-gnu, but are `long` on everything else-linux-gnu, which is not yet implemented there. A fix for this is in progress.
Please note that this is a bug at the top of a minor pit of issues on s390x that we are currently still working on.

**Comment by fidencio** [comment]
@Jakob-Naucke, thanks for the very quick and detailed answer.  I'll leave this issue opened so we can refer to this whenever progress is made, and distro maintainers will be eable to check its status here. :-).

@etrunko, please, let's push forward the Fedora packaging excluding s390x for now, and linking to this issue.

Thanks to both of you!

**Comment by liubin** [comment]
Indeed there is two versions of `is_cgroup2_unified_mode`. We can use attributes to control it like this:

```
#[cfg(all(target_os = "linux", not(target_env = "musl")))]
pub fn is_cgroup2_unified_mode() -> bool {

#[cfg(all(target_os = "linux", target_env = "musl"))]
pub fn is_cgroup2_unified_mode() -> bool {
```

In s390x, only compile [this version](https://github.com/kata-containers/cgroups-rs/blob/master/src/hierarchies.rs#L230) will pass. `target_arch = "s390"` will be ok?

**Comment by Jakob-Naucke** [comment]
@liubin we could do that, but a [fix](https://github.com/rust-lang/libc/pull/1999) is now on the way. If you want to do it, be sure to use `s390x` (`s390` is 32bit). Since we are already not using musl on s390x, it would require an exception to s390x in the first directive, and an alternative to musl in the second.

**Comment by liubin** [comment]
@Jakob-Naucke Since you have fixed the root cause, there will no need to do such a workaround.
