### PR TITLE
ci: Fix failing static checks to enable IBM actionspz - Z specific

### PR DESCRIPTION
**Pull request by BbolroC**
This PR fixes errors for static-checks while integrating IBM actionspz runners into the CI.
For details, please check out each commit message. Thanks!

Signed-off-by: Hyounggyu Choi <Hyounggyu.Choi@ibm.com>

### CODE REVIEW

**Comment by BbolroC** [comment]
For reviewers, P specific issues will be handled in https://github.com/kata-containers/kata-containers/pull/11938 which should be merged after this PR. Thanks!

File: src/agent/src/mount.rs [hunk 1]
```diff
@@ -416,7 +428,7 @@ mod tests {
                 fs_type: "bind",
                 flags: MsFlags::empty(),
                 options: "bind",
-                error_contains: "Operation not permitted",
+                error_contains: get_error_msg("Operation not permitted", "No such device"),
```
Comment (stevenhorsman) [inline src/agent/src/mount.rs]: It feels like we could make this more obvious, maybe having a constant string or default_error and btrs_error and passing them through here?

**Comment by stevenhorsman** [comment]
The agent test failed with ` netlink::tests::test_add_one_arp_neighbor`, so can we rebase it to try and remove the chance of that happening?

File: src/agent/src/mount.rs (hunk 1 above)
Comment (BbolroC) [reply src/agent/src/mount.rs]: Will do. Thanks for suggestion!

**Comment by BbolroC** [comment]
> The agent test failed with  netlink::tests::test_add_one_arp_neighbor, so can we rebase it to try and remove the chance of that happening?

Yep, I am going to rebase this on main when reflecting your suggestion. Thanks a lot!

File: src/agent/src/mount.rs [hunk 2]
```diff
@@ -381,6 +381,22 @@ mod tests {
         let drain = slog::Discard;
         let logger = slog::Logger::root(drain, o!());
 
+        // Detect filesystem type of root directory
```
Comment (wainersm) [inline src/agent/src/mount.rs:390]: Hi @BbolroC !

If it was checking the error number instead of message then maybe it would work on different filesystems and no adaptations would be needed? Although "not permitted" and "no such device" are different errors... I'm just thinking aloud...

I think that checking the message is error prone. The test would be more reliable if it was checking the error number.

Your fix is fine anyway.

File: src/agent/src/mount.rs [hunk 3]
```diff
@@ -496,7 +512,14 @@ mod tests {
 
             let err = result.unwrap_err();
             let error_msg = format!("{}", err);
-            assert!(error_msg.contains(d.error_contains), "{}", msg);
+
+            assert!(
```
Comment (wainersm) [inline src/agent/src/mount.rs:522]: `assert_matches` could be used here, although it's an experimental function yet, so you don't need to print the actual vs expected value yourself.

https://doc.rust-lang.org/std/assert_matches/macro.assert_matches.html

File: src/libs/test-utils/src/lib.rs [hunk 4]
```diff
@@ -95,6 +95,80 @@ macro_rules! skip_loop_by_user {
...
+                        );
+                        return;
+                    }
+                }
+
+                // Try RNDRESEEDCRNG ioctl (same as reseed_rng)
+                let ret = unsafe { libc::ioctl(fd, RNDRESEEDCRNG as IoctlRequestType, 0) };
+                let _ = nix::unistd::close(fd);
+
+                if let Err(e) = Errno::result(ret).map(drop) {
```
Comment (wainersm) [inline src/libs/test-utils/src/lib.rs]: Hi @BbolroC , this function is scary :D

What if we parse the value of `ret` in `let ret = reseed_rng(&seed);` just like you did here, and if EPERM then assume the test succeeded? Because IIUC `reseed_rng` will return the return from `libc::ioctl` anyways.

Makes sense?

File: src/agent/src/netlink.rs [hunk 5]
```diff
@@ -1045,10 +1045,18 @@ mod tests {
         let lo = handle.find_link(LinkFilter::Name("lo")).await.unwrap();
 
         for network in list {
-            handle
-                .add_addresses(lo.index(), iter::once(network))
-                .await
-                .expect("Failed to add IP");
+            let result = handle.add_addresses(lo.index(), iter::once(network)).await;
```
Comment (wainersm) [inline src/agent/src/netlink.rs:1060]: My comment on previous commit, regarding `reseed_rng()`, was to implement something similar to what you did here.

File: src/agent/src/rpc.rs [hunk 6]
```diff
@@ -2481,6 +2481,26 @@ mod tests {
...
         m.name = "bridge".to_string();
         let result = load_kernel_module(&m);
+
+        // Skip test if loading kernel modules is not permitted
+        // or kernel module is not found
+        if let Err(e) = &result {
+            let error_string = format!("{:?}", e);
+            // Let's print out the error message first
+            println!("DEBUG: error: {}", error_string);
+            if error_string.contains("Operation not permitted")
```
Comment (wainersm) [inline src/agent/src/rpc.rs:2491]: Would be possible to check the error number instead of the message? Less error prone IMO.

File: src/agent/src/mount.rs (hunk 2 above)
Comment (BbolroC) [reply src/agent/src/mount.rs:390]: Yeah, the message does not have any numbers. But let me check it again. Thanks!

File: src/agent/src/mount.rs (hunk 3 above)
Comment (BbolroC) [reply src/agent/src/mount.rs:522]: Yep, I will use `assert_matches!()` then. Thanks for suggestion. 😉

File: src/libs/test-utils/src/lib.rs (hunk 4 above)
Comment (BbolroC) [reply src/libs/test-utils/src/lib.rs]: Hehe, I was thinking that too after I got an approval from Steve. Yep, let's check an error from `let ret = reseed_rng(&seed);`. Thanks!

File: src/agent/src/netlink.rs (hunk 5 above)
Comment (BbolroC) [reply src/agent/src/netlink.rs:1060]: Yep, I understood your comment correctly. 😉

File: src/agent/src/rpc.rs (hunk 6 above)
Comment (BbolroC) [reply src/agent/src/rpc.rs:2491]: Yep, let me revisit the error message if it contains any number. Thanks!

File: src/agent/src/mount.rs (hunk 2 above)
Comment (BbolroC) [reply src/agent/src/mount.rs:390]: The error message from nix is either:

```
ENODEV: No such device
```

or

```
EPERM: Operation not permitted
```

So I will keep my approach here. Thanks!

File: src/agent/src/rpc.rs (hunk 6 above)
Comment (BbolroC) [reply src/agent/src/rpc.rs:2491]: The error message is:

```
modprobe: FATAL: Module bridge not found in directory /lib/modules/6.8.0-85-generic
```

Comment (BbolroC) [reply src/agent/src/rpc.rs:2491]: Here is what I got from `modprobe`:

```
# modprobe nonexistentmodule
modprobe: FATAL: Module nonexistentmodule not found in directory /lib/modules/6.8.0-83-generic
# modprobe nonexistentmodule 2>/dev/null; echo "Exit code: $?"
Exit code: 1
$ modprobe zfs
modprobe: ERROR: could not insert 'zfs': Operation not permitted
$ modprobe zfs 2>/dev/null; echo "Exit code: $?"
Exit code: 1
```

Two different errors have the same error code. So I would like to keep the existing code because only the error case for either `not found` or `not permitted` is what we want to skip.

File: src/agent/src/mount.rs (hunk 3 above)
Comment (BbolroC) [reply src/agent/src/mount.rs:522]: I got the following error (see [log](https://github.com/kata-containers/kata-containers/actions/runs/18748596430/job/53481956192?pr=11924)):

```
error[E0658]: use of unstable library feature `assert_matches`
   --> src/mount.rs:523:13
    |
523 |             assert_matches!(error_msg.as_str(), s if s.contains(d.error_contains));
    |             ^^^^^^^^^^^^^^
    |
    = note: see issue #82775 <https://github.com/rust-lang/rust/issues/82775> for more information
```

I will use assert!() again. Thanks!

**Comment by BbolroC** [comment]
@wainersm I think the PR is ready to go. The CI failures for runtime have nothing to do with the change and are caused by https://github.com/kata-containers/kata-containers/pull/10664#issuecomment-3441823588. Thanks!

---

FYI: A [fix](https://github.com/kata-containers/kata-containers/pull/11975) for the issue is underway.

File: src/agent/src/mount.rs (hunk 2 above)
Comment (wainersm) [reply src/agent/src/mount.rs:390]: hi @BbolroC , good to know. Thanks for checking it out!

File: src/agent/src/mount.rs (hunk 3 above)
Comment (wainersm) [reply src/agent/src/mount.rs:522]: Yeah, `assert_matches` seems to be experimental yet. It is something to keep eyes on, when it becomes stable feature.

File: src/agent/src/rpc.rs (hunk 6 above)
Comment (wainersm) [reply src/agent/src/rpc.rs:2491]: ok;

**Comment by BbolroC** [comment]
@stevenhorsman Could you help resolve the pending s390x static checks (required)? It looks they are old GHA CI job names. Thanks!
