### PR TITLE
fix build with go 1.14

### PR DESCRIPTION
**Pull request by bergwolf**
There are several issues:
1. vendor/modules.txt is not consistent with go.mod
2. runtime does not depend on go agent any more
3. go 1.14 backtrace is a bit different than older go runtime

Also add a few build targets in makefile to facilitate build and test.

### CODE REVIEW

**Comment by jodh-intel** [comment]
Thanks @bergwolf. Travis is complaining though:

```
   Compiling protocols v0.1.0 (/home/travis/gopath/src/github.com/kata-containers/kata-containers/src/agent/protocols)
error[E0433]: failed to resolve: could not find `client_request` in `ttrpc`
  --> protocols/src/agent_ttrpc.rs:42:18
   |
42 |         ::ttrpc::client_request!(self, req, timeout_nano, "grpc.AgentService", "CreateContainer", cres);
   |                  ^^^^^^^^^^^^^^ could not find `client_request` in `ttrpc`

```

Not sure if that's a `protoc` / `ttrpc_rust_plugin` issue?

**Comment by bergwolf** [comment]
sob-check hangs. Otherwise this can be merged.
