### ISSUE TITLE
Kata fails to build with Rust 1.79

### ISSUE THREAD

**Issue by emanuellima1** [kata-containers/kata-containers#10067]
# Description of problem

When trying to build kata-containers on Linux using rustc v1.79, the following error occurs:

```bash
Compiling kata-agent v0.1.0 ($PWD/kata-containers/kata-containers-3.7.0/src/agent)
error: field `supports_seccomp` is never read
   --> src/config.rs:106:9
    |
94  | pub struct AgentConfig {
    |            ----------- field in this struct
...
106 |     pub supports_seccomp: bool,
    |         ^^^^^^^^^^^^^^^^
    |
    = note: `AgentConfig` has a derived impl for the trait `Debug`, but this is intentionally ignored during dead code analysis
    = note: `-D dead-code` implied by `-D warnings`
    = help: to override `-D warnings` add `#[allow(dead_code)]`

error: could not compile `kata-agent` (bin "kata-agent") due to 1 previous error
make: *** [Makefile:137: target/x86_64-unknown-linux-gnu/release/kata-agent] Error 101
erro: Status de saída de /var/tmp/rpm-tmp.WB29w7 inválido (%build)
```

This was specifically when building a RPM for Fedora 40, but it fails to build with the same error when compiling just the repo. This has been observed for both Kata 3.7.0 and HEAD.

Compiling with Rust v1.78 works fine. 

# Expected result

I expected the RPM and/or the binary to be built normally, as it does with Rust v1.78.

# Actual result

Rust compilation error when compiling the kata-agent binary

**Comment by emanuellima1** [comment]
FYI: this bug is blocking the update of kata-containers on Fedora 40 and Rawhide.

**Comment by zvonkok** [comment]
How are you kicking off the build?
Is libseccomp installed via package manager? 
We usually build libseccomp alongside the kata-agent to make sure they're compatible.

**Comment by emanuellima1** [comment]
It has been installed via package manager. I'm building just the kata-agent by doing make on it's makefile only. Is this wrong?

```bash
libseccomp.so.2 (libc6,x86-64) => /lib64/libseccomp.so.2
libseccomp.so (libc6,x86-64) => /lib64/libseccomp.so
```

```bash
-lseccomp
```

**Comment by c3d** [comment]
I tried with rustc 1.80.0 from rustup, and 

```
   Compiling kata-sys-util v0.1.0 (/home/ddd/Work/kata/kata-containers/src/libs/kata-sys-util)
error: unexpected `cfg` condition value: `powerpc64le`
  --> /home/ddd/Work/kata/kata-containers/src/libs/kata-sys-util/src/protection.rs:17:34
   |
17 | #[cfg(any(target_arch = "s390x", target_arch = "powerpc64le"))]
   |                                  ^^^^^^^^^^^^^^-------------
   |                                                |
   |                                                help: there is a expected value with a similar name: `"powerpc64"`
   |
   = note: expected values for `target_arch` are: `aarch64`, `arm`, `arm64ec`, `avr`, `bpf`, `csky`, `hexagon`, `loongarch64`, `m68k`, `mips`, `mips32r6`, `mips64`, `mips64r6`, `msp430`, `nvptx64`, `powerpc`, `powerpc64`, `riscv32`, `riscv64`, `s390x`, `sparc`, `sparc64`, `wasm32`, `wasm64`, `x86`, and `x86_64`
   = note: see <https://doc.rust-lang.org/nightly/rustc/check-cfg/cargo-specifics.html> for more information about checking conditional configuration
   = note: `-D unexpected-cfgs` implied by `-D warnings`
   = help: to override `-D warnings` add `#[allow(unexpected_cfgs)]`

error: unexpected `cfg` condition value: `powerpc64le`
   --> /home/ddd/Work/kata/kata-containers/src/libs/kata-sys-util/src/protection.rs:237:7
    |
237 | #[cfg(target_arch = "powerpc64le")]
    |       ^^^^^^^^^^^^^^-------------
    |                     |
    |                     help: there is a expected value with a similar name: `"powerpc64"`
    |
    = note: expected values for `target_arch` are: `aarch64`, `arm`, `arm64ec`, `avr`, `bpf`, `csky`, `hexagon`, `loongarch64`, `m68k`, `mips`, `mips32r6`, `mips64`, `mips64r6`, `msp430`, `nvptx64`, `powerpc`, `powerpc64`, `riscv32`, `riscv64`, `s390x`, `sparc`, `sparc64`, `wasm32`, `wasm64`, `x86`, and `x86_64`
    = note: see <https://doc.rust-lang.org/nightly/rustc/check-cfg/cargo-specifics.html> for more information about checking conditional configuration

error: could not compile `kata-sys-util` (lib) due to 2 previous errors
```

I think that I will open an issue for that.

**Comment by emanuellima1** [comment]
So, in the end, the linking problem just appeared when I tried to build kata-agent from it's folder. When I build runtime-rs it works, presumably because it uses the correct libseccomp. I'll open a PR for this.

**Comment by zvonkok** [comment]
Try to use the Makefile targets for building each component for reliable and repeatable builds. 
```
$ make agent-tarball
```
If you build the runtime components you should do a 

```
$ make shim-v2-tarball
``` 
I do not know how and which component you're packaging with Fedora but it would be good to "always" use the Makefile targets.

**Comment by c3d** [comment]
> Try to use the Makefile targets for building each component for reliable and repeatable builds.
> 
> ```
> $ make agent-tarball
> ```
> 
> If you build the runtime components you should do a
> 
> ```
> $ make shim-v2-tarball
> ```
> 
> I do not know how and which component you're packaging with Fedora but it would be good to "always" use the Makefile targets.

I don't think that this works in the context where @emanuellima1 is doing the build, because it requires root access and docker to build, right? I don't think that you can do that in the Fedora build environment.

**Comment by emanuellima1** [comment]
I'm also building outside of a Fedora context, so I'll try this as well

**Comment by c3d** [comment]
I was able to reproduce the `-lseccomp` issue with 1.78 from rustup. Tracking it down through the command line, it appears that this is because there is no static version of `libseccomp` on Fedora. For other libraries, the Rust musl build environments provides a static equivalent (e.g. libunwind), but libseccomp is missing.

So far, I was not able to reproduce the error about the field never being read. I'm curious if this is a 1.79-only thing (i.e. not in 1.78 nor in 1.80).

**Comment by emanuellima1** [comment]
AFAIK, it's only on 1.79

**Comment by c3d** [comment]
Confirmed, it is only 1.79. So the good news is that it's gone in 1.80.

**Comment by albertlarsan68** [comment]
Hello,

> Confirmed, it is only 1.79. So the good news is that it's gone in 1.80.

Please search if an issue exists (and file a new one if no one exists) about the regression or false positive at https://github.com/rust-lang/rust
